export default [
    { id: "10", name: "Construction / Civil Engineering" },
    { id: "7", name: "Banking / Financial Services / Broking" },
    { id: "36", name: "Oil & Gas / Petroleum" },
    { id: "25", name: "IT - Software Services" },
    { id: "30", name: "Medical / Healthcare / Diagnostics / Medical Devices" },
    { id: "20", name: "Hotels / Hospitality" },
    { id: "55", name: "Accounting & Auditing" },
    { id: "2", name: "Advertising / PR / Event Management" },
    { id: "3", name: "Agriculture / Dairy / Poultry / Livestock" },
    { id: "52", name: "Air Conditioning / Refrigeration / HVAC" },
    { id: "4", name: "Airlines / Aviation" },
    { id: "5", name: "Architecture / Interior Designing" },
    { id: "6", name: "Automotive / Automobile / Auto Accessories" },
    { id: "56", name: "Call Center / BPO / KPO / Outsourcing" },
    { id: "57", name: "Ceramics / Sanitary ware" },
    { id: "9", name: "Chemicals / Petrochemicals / Polymers / Industrial Gases" },
    { id: "58", name: "Concrete / Readymix / Cement" },
    { id: "59", name: "Consulting / Management Consulting / Advisory Services" },
    { id: "11", name: "Consumer Durables / Consumer Electronics" },
    { id: "14", name: "Defence / Military / Government" },
    { id: "15", name: "Education / Training / Teaching / Academics" },
    { id: "60", name: "Elevators / Escalators" },
    { id: "61", name: "Engineering Design & Consulting" },
    { id: "62", name: "Entertainment / Recreation / Theme Parks" },
    { id: "63", name: "Facilities Management" },
    { id: "17", name: "Fertilizers / Pesticides" },
    { id: "64", name: "Fitness / Wellness / Gym / Salon / Spa" },
    { id: "12", name: "FMCG / Foods / Beverages" },
    { id: "18", name: "Fresher - No Industry Experience / Not Employed" },
    { id: "65", name: "Furniture / Furnishings / Home Décor" },
    { id: "16", name: "General Trading / Export / Import" },
    { id: "66", name: "Glass" },
    { id: "19", name: "Gold / Gems & Jewellery" },
    { id: "21", name: "Industrial Products / Heavy Machinery" },
    { id: "22", name: "Insurance" },
    { id: "23", name: "Internet / E-commerce / Dotcom" },
    { id: "24", name: "IT - Hardware & Networking" },
    { id: "67", name: "Landscaping" },
    { id: "68", name: "Legal / Law Firm" },
    { id: "13", name: "Logistics / Transportation / Warehousing / Courier" },
    { id: "29", name: "Media / Publishing / TV / Radio / Outdoor / Digital" },
    { id: "31", name: "Metals / Steel / Iron / Aluminium / Fabrication" },
    { id: "69", name: "Metro / Railway / Train" },
    { id: "54", name: "Mining / Forestry / Fishing" },
    { id: "32", name: "NGO / Social Services / Community Services / Non-Profit " },
    { id: "34", name: "Office Automation / Office Equipment / Office Supplies / Stationery " },
    { id: "70", name: "Oil & Gas: Consultancy, Design, FEED" },
    { id: "71", name: "Oil & Gas: Exploration, Drilling, Production, Field Services" },
    { id: "72", name: "Oil & Gas: Refining, Storage, Marketing, Distribution" },
    { id: "1000", name: "Other" },
    { id: "35", name: "Paper / Paper Pulp / Paper Mill" },
    { id: "73", name: "Perfumery / Toiletries / Personal Care / Cosmetics" },
    { id: "37", name: "Pharma / Biotech / Clinical Research" },
    { id: "38", name: "Plastics / Rubber" },
    { id: "39", name: "Power Generation / Power Distribution / Energy / Nuclear Energy" },
    { id: "40", name: "Printing / Packaging" },
    { id: "41", name: "Real Estate" },
    { id: "42", name: "Recruitment / Placement Firm / Executive Search" },
    { id: "53", name: "Restaurants / Catering / Food Services" },
    { id: "43", name: "Retail" },
    { id: "45", name: "Security / Law Enforcement" },
    { id: "74", name: "Shipbuilding / Ship Repair / Ship Maintenance / Drydocks" },
    { id: "46", name: "Shipping / Freight" },
    { id: "47", name: "Telecom / ISP" },
    { id: "75", name: "Testing / Inspection / Certification Services" },
    { id: "49", name: "Textiles  Clothing / Apparels / Fashion / Accessories" },
    { id: "76", name: "Travel / Tourism" },
    { id: "50", name: "Tyres" },
    { id: "77", name: "Water Treatment / De-Salination / Waste Management" }
];
